### ISSUE TITLE
demo/mdlstm/IAM use_tensorflow:true ---> Exception: unknown layer class 'mdlstm'

### ISSUE THREAD

**Issue by rogerzico** [rwth-i6/returnn#35] opened 2018-02-15 09:56 UTC
try to run demo/mdlstm/IAM with "use_tensorflow:true" added to config_real

but got  ---> Exception: unknown layer class 'mdlstm'.

Thanks!

**Comment by pvoigtlaender** [comment] 2018-02-15 10:06
Hi,

unfortunately our mdlstm implementation is for thano only, so you can't use the tensorflow backend for that.

**Comment by rogerzico** [comment] 2018-02-15 19:37
Hi,

Could you give me some directions if I want to "hack into" it myself?

Thanks

**Comment by rogerzico** [comment] 2018-02-16 06:34
I got rid of "use_tensorflow:true" from config_real, and "./go.sh",

Here is another exception:
......
  File "/home/ubuntu/temp/returnn/Updater.py", line 4, in <module>
    line: import theano
    locals:
      theano = <not found>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 116, in <module>
    line: theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
    locals:
      theano = <local> <module 'theano' from '/usr/local/lib/python2.7/dist-packages/theano/__init__.pyc'>
      theano.sandbox = <local> <module 'theano.sandbox' from '/usr/local/lib/python2.7/dist-packages/theano/sandbox/__init__.pyc'>
      theano.sandbox.cuda = <local> <module 'theano.sandbox.cuda' from '/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.pyc'>
      theano.sandbox.cuda.tests = <local> <module 'theano.sandbox.cuda.tests' from '/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/tests/__init__.pyc'>
      theano.sandbox.cuda.tests.test_driver = <local> <module 'theano.sandbox.cuda.tests.test_driver' from '/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/tests/test_driver.pyc'>
      theano.sandbox.cuda.tests.test_driver = <local> <module 'theano.sandbox.cuda.tests.test_driver' from '/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/tests/test_driver.pyc'>
      theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1 = <local> <function test_nvidia_driver1 at 0x7ffb30ab4cf8>
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/tests/test_driver.py", line 41, in test_nvidia_driver1
    line: raise Exception("The nvidia driver version installed with this OS "
    locals:
      Exception = <builtin> <type 'exceptions.Exception'>
Exception: The nvidia driver version installed with this OS does not give good results for reduction.Installing the nvidia driver available on the same download page as the cuda package will fix the problem: http://developer.nvidia.com/cuda-downloads
Device proc gpuX (gpuZ) died: ProcConnectionDied('recv_bytes EOFError: ',)
Theano flags: compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,force_device=True
EXCEPTION
Traceback (most recent call last):
  File "/home/ubuntu/temp/returnn/Device.py", line 347, in startProc
    line: self._startProc(*args, **kwargs)
    locals:
      self = <local> <Device.Device object at 0x7ff35acd5cd0>
      self._startProc = <local> <bound method Device._startProc of <Device.Device object at 0x7ff35acd5cd0>>
      args = <local> ('gpuZ',)
      kwargs = <local> {}
  File "/home/ubuntu/temp/returnn/Device.py", line 401, in _startProc
    line: interrupt_main()
    locals:
      interrupt_main = <global> <function interrupt_main at 0x7ff35b881668>
  File "/home/ubuntu/temp/returnn/Util.py", line 665, in interrupt_main
    line: sys.exit(1)  # And exit the thread.
    locals:
      sys = <global> <module 'sys' (built-in)>
      sys.exit = <global> <built-in function exit>
SystemExit: 1
KeyboardInterrupt
EXCEPTION
Traceback (most recent call last):
  File "../../../rnn.py", line 539, in main
    line: init(commandLineOptions=argv[1:])
    locals:
      init = <global> <function init at 0x7ff35accd1b8>
      commandLineOptions = <not found>
      argv = <local> ['../../../rnn.py', 'config_real'], _[0]: {len = 15}
  File "../../../rnn.py", line 341, in init
    line: devices = initDevices()
    locals:
      devices = <not found>
      initDevices = <global> <function initDevices at 0x7ff35acccd70>
  File "../../../rnn.py", line 154, in initDevices
    line: time.sleep(0.25)
    locals:
      time = <global> <module 'time' (built-in)>
      time.sleep = <global> <built-in function sleep>
KeyboardInterrupt
Quitting

**Comment by pvoigtlaender** [comment] 2018-02-16 10:56
Hi,

the important part of the messages is this:

```
The nvidia driver version installed with this OS does not give good results for reduction.Installing the nvidia driver available on the same download page as the cuda package will fix the problem: http://developer.nvidia.com/cuda-downloads
```

Please try another nvidia driver

**Comment by rogerzico** [comment] 2018-02-16 18:30
Hi,

"If you want to look further into this, I can give you a few more details."
Yes, please send me the details. I am interested in making this work.
Thanks!

**Comment by rogerzico** [comment] 2018-02-16 23:21
Hi,
With regard to the error message:
"
The nvidia driver version installed with this OS does not give good results for reduction.Installing the nvidia driver available on the same download page as the cuda package will fix the problem: http://developer.nvidia.com/cuda-downloads
"
I upgraded to nvidia-390, but still got this error ???!!!
Here is the HW/SW configuration:

Aws, p2.xlarge  --- Tesla K80
nvidia 390
theano 0.9.0,
pygpu 0.6.9

Tried 
---
%python ../../../rnn.py config_demo
>>>>"Could not find cudnn library (looked for v5[.1])
---

Tried 
---
%THEANO_FLAGS=device=gpu python ../../../rnn.py config_demo
>>>> "... does not give good results ...."
---

Please advice!

Thanks

**Comment by pvoigtlaender** [comment] 2018-02-17 11:30
> "Could not find cudnn library (looked for v5[.1])

Have a look at http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html on how to setup cudnn for theano

> The nvidia driver version installed with this OS does not give good results for reduction.Installing the nvidia driver available on the same download page as the cuda package will fix the problem

I also don't know much about that. Might be related to the version of theano, are you using 0.9 or 1.0? It should be worth trying 0.9. A google search for the error message brought up quite some results, e.g. https://github.com/Theano/Theano/issues/5530

**Comment by pvoigtlaender** [comment] 2018-02-17 11:33
For a possible port of mdlstm to tensorflow:
The mdlstm implementation is mainly here: https://github.com/rwth-i6/returnn/blob/master/cuda_implementation/MultiDirectionalTwoDLSTMOp.py
Here, we derive from theano.sandbox.cuda.GpuOp to define a theano Op. You would need to create a different wrapper for tensorflow, you can find some information about this here (pay special attention to the GPU kernel parts): https://www.tensorflow.org/extend/adding_an_op

**Comment by rogerzico** [comment] 2018-02-17 20:54
Danke!

**Comment by albertz** [comment] 2018-02-20 00:42
Is this bug now only about MDLSTM in TensorFlow? Then this is just a duplicate of #8.

**Comment by rogerzico** [comment] 2018-02-21 18:07
@albertz 
more like an unfinished feature than a bug!

**Comment by albertz** [comment] 2018-02-21 18:19
Yea. Ok, then I'm closing this now. Anything related to MDLSTM in TF should be discussed in #8. If there is another separate issue, please open a separate issue.

**Closed by albertz** 2018-02-21 18:19 UTC
