### ISSUE TITLE
Random_normal during forward: must feed size tensor

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn#1121] opened 2022-09-12 08:21 UTC
I am currently working on random sampling and while training with a config worked flawlessly, using the config for inference causes problems. I assume this is only happening because during training I am using `declare_same_as` for a loss, but this does not work for forward since I am doing upsampling with lengths the model predicts, so there will be a mismatch if I just put `declare_same_as`  (Error goes away but a different shape mismatch error occurs). But this only for context, now to the problem.

```
TensorFlow exception: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
         [[random/random/stateful_normal/_17]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'extern_data/placeholders/audio_features/audio_features_dim0_size':
  File "u/hilmes/returnn/rnn.py", line 11, in <module>
    main()
  File "u/hilmes/returnn/returnn/__main__.py", line 657, in main
    execute_main_task()
  File "u/hilmes/returnn/returnn/__main__.py", line 489, in execute_main_task
    engine.init_network_from_config(config)
  File "u/hilmes/returnn/returnn/tf/engine.py", line 1121, in init_network_from_config
    self._init_network(net_desc=net_dict, epoch=self.epoch)
  File "u/hilmes/returnn/returnn/tf/engine.py", line 1297, in _init_network
    extern_data.init_from_config(config=self.config, auto_create_placeholders=not use_dataset_pipeline)
  File "u/hilmes/returnn/returnn/tf/network.py", line 68, in init_from_config
    self.data[key] = Data(name=key, auto_create_placeholders=auto_create_placeholders, **init_args)
  File "u/hilmes/returnn/returnn/tf/util/data.py", line 2733, in __init__
    _auto_create_size_placeholders_on_dim_tags(name=name, dim_tags=dim_tags)
  File "u/hilmes/returnn/returnn/tf/util/data.py", line 5790, in _auto_create_size_placeholders_on_dim_tags
    _create_size_placeholder(name=name, axis_wo_b=axis_wo_b, tag=tag, batch_dim=batch_dim_)
  File "u/hilmes/returnn/returnn/tf/util/data.py", line 5651, in _create_size_placeholder
    dyn_size = tf_compat.v1.placeholder(
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 3100, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6808, in placeholder
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

Exception InvalidArgumentError() in step 0. (pid 2438)
Failing op: <tf.Operation 'extern_data/placeholders/audio_features/audio_features_dim0_size' type=Placeholder>
Used by: [<tf.Operation 'extern_data/placeholders/audio_features/batch_dim/Shape' type=Shape>]
  File "/u/hilmes/returnn/rnn.py", line 11, in <module>
    main()                                                                                                                                                                        [201/1980]  File "/u/hilmes/returnn/returnn/__main__.py", line 657, in main
    execute_main_task()
  File "/u/hilmes/returnn/returnn/__main__.py", line 489, in execute_main_task
    engine.init_network_from_config(config)
  File "/u/hilmes/returnn/returnn/tf/engine.py", line 1121, in init_network_from_config
    self._init_network(net_desc=net_dict, epoch=self.epoch)
  File "/u/hilmes/returnn/returnn/tf/engine.py", line 1297, in _init_network
    extern_data.init_from_config(config=self.config, auto_create_placeholders=not use_dataset_pipeline)
  File "/u/hilmes/returnn/returnn/tf/network.py", line 79, in init_from_config
    self.init_batch_info()
  File "/u/hilmes/returnn/returnn/tf/network.py", line 159, in init_batch_info
    batch_dim = get_shape_dim(data.size_placeholder[0], 0, name="batch_dim")
  File "/u/hilmes/returnn/returnn/tf/util/basic.py", line 879, in get_shape_dim
    return tf.shape(x)[axis]
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 601, in shape_v2
    return shape(input, name, out_type)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 628, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 656, in shape_internal
    return gen_array_ops.shape(input, name=name, out_type=out_type)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9035, in shape
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

Input to output:
[<tf.Operation 'extern_data/placeholders/audio_features/audio_features_dim0_size' type=Placeholder>,
 <tf.Operation 'extern_data/placeholders/audio_features/batch_dim/Shape' type=Shape>,
 <tf.Operation 'extern_data/placeholders/audio_features/batch_dim/strided_slice' type=StridedSlice>,
 <tf.Operation 'random/random/stateful_normal/shape' type=Pack>,
 <tf.Operation 'random/random/stateful_normal/StatefulStandardNormalV2' type=StatefulStandardNormalV2>,
 <tf.Operation 'random/random/stateful_normal/mul' type=Mul>,
 <tf.Operation 'random/random/stateful_normal' type=Add>]
Step meta information:
{'seq_idx': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 'seq_tag': ['train-clean-100/7859-102521-0000/7859-102521-0000',
             'train-clean-100/3259-158083-0039/3259-158083-0039',
             'train-clean-100/1183-128659-0018/1183-128659-0018',
             'train-clean-100/8063-274117-0028/8063-274117-0028',
             'train-clean-100/7278-91083-0002/7278-91083-0002',
             'train-clean-100/2843-152918-0005/2843-152918-0005',
             'train-clean-100/1926-147979-0049/1926-147979-0049',
             'train-clean-100/4195-17507-0023/4195-17507-0023',
             'train-clean-100/1447-130550-0021/1447-130550-0021',
             'train-clean-100/4680-16042-0027/4680-16042-0027',
             'train-clean-100/5022-29411-0018/5022-29411-0018',
             'train-clean-100/2002-139469-0115/2002-139469-0115',
             'train-clean-100/3436-172162-0052/3436-172162-0052',
             'train-clean-100/8975-270782-0114/8975-270782-0114',
             'train-clean-100/3242-8112-0009/3242-8112-0009',
             'train-clean-100/1455-138263-0002/1455-138263-0002']}
Feed dict:
  <tf.Tensor 'extern_data/placeholders/phonemes/phonemes:0' shape=(?, ?) dtype=int32>: shape (16, 51), dtype int32, min/max 0/42, Data{'phonemes', [B,T|'phonemes_time'[B]], dtype='int32', sparse_dim=Dim{F'phonemes_indices'(44)}}
  <tf.Tensor 'extern_data/placeholders/phonemes/phonemes_dim0_size:0' shape=(?,) dtype=int32>: shape (16,), dtype int32, min/max 18/51, ([18 24 27 26 39 34 32 41 29 35 38 27 46 46 51 40])
  <tf.Tensor 'extern_data/placeholders/seq_tag/seq_tag:0' shape=(?,) dtype=string>: type <class 'list'>, Data{'seq_tag', [B?], dtype='string'}
EXCEPTION
Traceback (most recent call last):
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1365, in BaseSession._do_call
    line: return fn(*args)
    locals:
      fn = <local> <function BaseSession._do_run.<locals>._run_fn at 0x7f9116435af0>
      args = <local> ({<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f915728cdf0>: array([[42, 41,  9,  2, 41,  5, 19,  2, 22,  2, 19, 20,  1, 28, 30, 28,
                             41, 40,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                              0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                         ...
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1349, in BaseSession._do_run.<locals>._run_fn
    line: return self._call_tf_sessionrun(options, feed_dict, fetch_list,
                                          target_list, run_metadata)
    locals:
      self = <local> <tensorflow.python.client.session.Session object at 0x7f9154d74b20>
      self._call_tf_sessionrun = <local> <bound method BaseSession._call_tf_sessionrun of <tensorflow.python.client.session.Session object at 0x7f9154d74b20>>
      options = <local> None
      feed_dict = <local> {<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f915728cdf0>: array([[42, 41,  9,  2, 41,  5, 19,  2, 22,  2, 19, 20,  1, 28, 30, 28,
                                  41, 40,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                                   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                               ...
      fetch_list = <local> [<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f91573a3b30>]
      target_list = <local> []
      run_metadata = <local> None
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1441, in BaseSession._call_tf_sessionrun
    line: return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
                                                  fetch_list, target_list,
                                                  run_metadata)
    locals:
      tf_session = <global> <module 'tensorflow.python.client.pywrap_tf_session' from '/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/pywrap_tf_session.py'>
      tf_session.TF_SessionRun_wrapper = <global> <built-in method TF_SessionRun_wrapper of PyCapsule object at 0x7f923b7c5cf0>
      self = <local> <tensorflow.python.client.session.Session object at 0x7f9154d74b20>
      self._session = <local> <tensorflow.python._pywrap_tf_session.TF_Session object at 0x7f91574c47b0>
      options = <local> None
      feed_dict = <local> {<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f915728cdf0>: array([[42, 41,  9,  2, 41,  5, 19,  2, 22,  2, 19, 20,  1, 28, 30, 28,
                                  41, 40,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                                   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                               ...
      fetch_list = <local> [<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f91573a3b30>]
      target_list = <local> []
      run_metadata = <local> None
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[{{node extern_data/placeholders/audio_features/audio_features_dim0_size}}]]
         [[random/random/stateful_normal/_17]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[{{node extern_data/placeholders/audio_features/audio_features_dim0_size}}]]
0 successful operations.
0 derived errors ignored.
```

Then there is a similar exception below which ends with: 
```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
         [[random/random/stateful_normal/_17]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
0 successful operations.
0 derived errors ignored.
```

I was able to shrink down the network and the confusing part is: Even when removing the part that relies on the size tensor (e.g. upsampling etc.) the error persists as long as `nn.random_normal` is in the network.
The smallest net I was able to reproduce the error with was:
```
class NARTTSModel(nn.Module):
  def __init__(self):
    super(NARTTSModel, self).__init__()
    vae_lin_dim = nn.FeatureDim("vae_embedding", 512)
    self.vae_embedding = nn.Linear(vae_lin_dim)

  def __call__(self, text: nn.Tensor):
    vae_embedding = self.vae_embedding(text)
    rand = nn.random_normal(vae_embedding.shape_ordered)
    return rand
```
When removing the `random_normal` part this works.

A gist with the shrinked returnn config is here: [returnn.config](https://gist.github.com/Atticus1806/5cc9ff3e7bc32666af2be34e025e7d9d)

**Comment by albertz** [comment] 2022-09-13 07:15
Oh, so this is now purely on RETURNN side? The config you posted, this reproduces the problem?

**Comment by Atticus1806** [comment] 2022-09-13 07:18
Yes, so the config I posted actually now crashed with the other data object (phonemes, message is the same otherwise) but I think this is because I also removed the dependency on this from the network.

**Comment by albertz** [comment] 2022-09-13 07:27
[Updated config which can run standalone (synth dataset)](https://gist.github.com/albertz/33ca93d5c597ed433561503f2f0f6558).

**Comment by albertz** [comment] 2022-09-13 07:30
I just looked at the net dict: This is wrong now. You don't have any dependency to the input anymore. Sure you get such error. You need to have a dep to the input.

**Comment by Atticus1806** [comment] 2022-09-13 07:32
okay, so back to this?
vae_embedding_dim = FeatureDim('vae_embedding', 256)
random_state_dim = FeatureDim('random-state', 3)
```python
network = {
  'output': {
    'class': 'copy',
    'from': 'random',
    'out_shape': {batch_dim, phonemes_time_dim, vae_embedding_dim}
  },
  'random': {
    'class': 'subnetwork',
    'from': [],
    'subnetwork': {
      'random_state_init': {
        'class': 'random_state_init',
        'out_dim': random_state_dim,
        'out_shape': {random_state_dim}
      },
      'random': {
        'class': 'random',
        'shape': (
          batch_dim,
          phonemes_time_dim,
          vae_embedding_dim
        ),
        'distribution': 'normal',
        'mean': 0.0,
        'stddev': 1.0,
        'explicit_state': 'state_var0',
        'auto_update_state': True,
        'shape_deps': ['base:data:phonemes']
      },
      'output': {
        'class': 'copy',
        'from': 'random',
        'out_shape': {batch_dim, phonemes_time_dim, vae_embedding_dim}
      },
      'state_var0': {
        'class': 'variable',
        'shape': [
          random_state_dim
        ],
        'param_name': 'param',
        'dtype': 'int64',
        'trainable': False,
        'init_by_layer': 'random_state_init'
      }
    },
    'out_shape': {batch_dim, phonemes_time_dim, vae_embedding_dim}
  }
}
```

**Comment by Atticus1806** [comment] 2022-09-13 07:34
> You need to have a dep to the input.

So I thought about this issue in the shrunken config too (also for the targets since they are not used in the network above), but in my original config the targets are also used, somewhere in the network as input, but I could remove that part without changing the error.

**Comment by albertz** [comment] 2022-09-13 07:34
Why the subnetwork, state var, copy layer, etc?

**Comment by albertz** [comment] 2022-09-13 07:35
`shape_deps` just say that some dim for the shape is dynamic, and it needs this other data/layer to first define the dim tag. So you always need that. I don't exactly understand your comment.

**Comment by Atticus1806** [comment] 2022-09-13 07:35
Network was created with returnn common, copied the output. But feel free to change/remove layers.

**Comment by albertz** [comment] 2022-09-13 07:35
> Network was created with returnn common, copied the output. But feel free to change/remove layers.

I don't understand. You already did that in your other config?

**Comment by Atticus1806** [comment] 2022-09-13 07:49
I think we are referring to different networks now. So what I posted this morning as a full config was the output of 
`nn.get_returnn_config().get_complete_py_code_str(net)` on the returnn_common code I posted initially in this issue. The network (which you said was wrong) is then a variant where I removed everything I could while still keeping the error message similar/same. Now the config I posted after your comment with "back to this" is a copy of what I posted this morning, so again auto created thats why it has these subnetwork definition etc. 

Does that all make sense or is something unclear?

**Comment by Atticus1806** [comment] 2022-09-13 07:51
>You need to have a dep to the input.

So all extern_data defined as available_for_inference need to be used? Or at least one?

**Comment by albertz** [comment] 2022-09-13 08:07
Yes you should always remove everything as much as possible (for example copy layer, subnetwork, etc), but with the constraint that it stays correct. You removed it in such a way that it became broken. A broken config surely leads to an error. I just say, remove as much as possible, while keeping it correct. More specifically here: Do not remove the `shape_deps`.

**Comment by albertz** [comment] 2022-09-13 08:09
The `shape_deps` define the deps for the shape. Here the shape is `(batch_dim, phonemes_time_dim, vae_embedding_dim)`. The only unknown dim here is `phonemes_time_dim`. So you need to have the dep to the layer which defines this dim. This is `data:phonemes`. Exactly like returnn-common is already putting it.

**Comment by albertz** [comment] 2022-09-13 08:21
Btw, I think I know the problem: It helps to look actually at the stacktrace. :P The missing tensor is defined in `init_batch_info`, i.e. that is the batch dim. `init_batch_info` takes it from the shape of some of the inputs. What input is a bit arbitrary. It must have `available_for_inference=True`, but that is the case here for both. The problem then is, that this input is otherwise never used, and thus it will not be feeded to `session.run`. And thus the error.

**Comment by Atticus1806** [comment] 2022-09-13 08:22
Okay so removing `audio_features` from my extern data solves the problem. So if you say that things that are not available for inference should not be there in forward then this is a user error. 
But: In a different model that does not use random I always had these unused extern_data without a problem. Even removing random from my network and not changing anything removes the error and lets the model run. So this is at least inconsitent behavior of returnn I think.

**Comment by albertz** [comment] 2022-09-13 08:27
> Okay so removing `audio_features` from my extern data solves the problem. So if you say that things that are not available for inference should not be there in forward then this is a user error.

No I don't say that. This is a bug in RETURNN. It should not get the batch dim from a tensor which is then not fed to the network.


> But: In a different model that does not use random I always had these unused extern_data without a problem. Even removing random from my network and not changing anything removes the error and lets the model run. So this is at least inconsitent behavior of returnn I think.

This is exactly what I just explained. It is arbitrary from what input it takes the batch dim.

**Comment by albertz** [comment] 2022-09-13 08:28
Test case in RETURNN:
```python
def test_engine_forward_shape_deps():
  # https://github.com/rwth-i6/returnn/issues/1121
  from returnn.tf.util.data import batch_dim, SpatialDim, FeatureDim
  phonemes_time_dim = SpatialDim('phonemes_time')
  phonemes_indices_dim = FeatureDim('phonemes_indices', 5)
  audio_time_dim = SpatialDim('phonemes_time')
  audio_feature_dim = FeatureDim('phonemes_indices', 4)
  vae_embedding_dim = FeatureDim('vae_embedding', 2)
  config = Config(dict(
    extern_data={
      'phonemes': {
        'dim_tags': (batch_dim, phonemes_time_dim),
        'dtype': 'int32',
        'sparse_dim': phonemes_indices_dim,
        'available_for_inference': True
      },
      'audio_features': {
        'dim_tags': (batch_dim, audio_time_dim, audio_feature_dim),
        'available_for_inference': True
      }
    },
    eval={
      "class": "MetaDataset",
      "data_map": {
        "audio_features": ("audio", "data"),
        "phonemes": ("audio", "classes"),
      },
      "datasets": {
        "audio": {
          "class": "Task12AXDataset",
          "num_seqs": 2,
        },
      },
      "seq_order_control_dataset": "audio",
    },
    network={
      'output': {
        'class': 'random',
        'shape': (batch_dim, phonemes_time_dim, vae_embedding_dim),
        'distribution': 'normal',
        'static': True,
      }
    },
    task="forward",
    allow_random_model_init=True,
  ))

  from returnn.datasets.basic import init_dataset
  engine = Engine(config=config)
  engine.init_network_from_config()
  engine.forward_single(dataset=init_dataset(config.typed_dict["eval"]), seq_idx=0)
```

**Comment by Atticus1806** [comment] 2022-09-13 08:28
Ah then I misunderstood you.

**Comment by albertz** [comment] 2022-09-13 08:38
> The problem then is, that this input is otherwise never used, and thus it will not be feeded to `session.run`.

It's not so obvious how to solve this. How do we know what input to use to determine the batch dim?

At the time when the batch dim is requested, we have not build the full network yet, so we don't know which of the data is used.

In the current implementation, this `init_batch_info` is called even before that, in the very beginning, so there we do not know anything about the network yet.

In this case here, as we have the dependency to `data:phonemes`, so we should know that `phonemes` can be used, once the batch dim is requested for the first time. But would that always be the case, that we know it then?

A cleaner approach is maybe to explicitly feed the batch dim to `session.run`. I was hesitating so far to do that, to not feed too much, but maybe that makes it just cleaner, and the overhead due to that should be negligible anyway?

**Comment by albertz** [comment] 2022-09-13 08:48
Just a side note: I just realized, this nice helpful "Used by: ..." output, this comes from our own `help_on_tf_exception`. I wondered why I did not see this in the test case. Because I did not use `help_on_tf_exception` in there.

**Comment by albertz** [comment] 2022-09-13 09:40
The PR #1122 should fix this.

**Comment by albertz** [comment] 2022-09-13 10:38
This should be fixed now.

**Closed** 2022-09-13 10:38 UTC
