### ISSUE TITLE
param_dropout doesn't work with TF2.4

### ISSUE THREAD

**Issue by jiangj-dc** [rwth-i6/returnn#1476] opened 2023-12-08 17:10 UTC
param_dropout doesn't work with TF2.4 and Python3.8
returnn commit: c4d36d06f6465e82a50d400d114259e07b8b0709

error output
```
  File "returnn/returnn/tf/util/basic.py", line 4444, in StatelessRandomSeed.create
    line: key, counter = generator._prepare_key_counter(shape)
  File "lib/python3.8/site-packages/tensorflow/python/ops/stateful_random_ops.py", line 630, in Generator._prepare_key_counter
    line: counter = array_ops.bitcast(counter_key[:counter_size], dtypes.uint64)
```

It appears that the issue is with lib/python3.8/site-packages/tensorflow/python/ops/stateful_random_ops.py
```
from tensorflow.python.compat import compat
...
  def skip(self, delta):
    """Advance the counter of a counter-based RNG.

    Args:
      delta: the amount of advancement. The state of the RNG after
        `skip(n)` will be the same as that after `normal([n])`
        (or any other distribution). The actual increment added to the
        counter is an unspecified implementation detail.
    """
    **if compat.forward_compatible(2020, 10, 25):**
      return gen_stateful_random_ops.rng_read_and_skip(
          self.state.handle,
          alg=math_ops.cast(self.algorithm, dtypes.int32),
          delta=math_ops.cast(delta, dtypes.uint64))
    **gen_stateful_random_ops.rng_skip(**
        self.state.handle, math_ops.cast(self.algorithm, dtypes.int64),
        math_ops.cast(delta, dtypes.int64))
...
```

If I comment out "**if compat.forward_compatible(2020, 10, 25):**", it will work.
Also, there is no return before **gen_stateful_random_ops.rng_skip**, and it seems to be a bug.

**Comment by albertz** [comment] 2023-12-08 22:41
Your error output seems very incomplete. Can you post the full stacktrace + the actual exception?

> It appears that the issue is with lib/python3.8/site-packages/tensorflow/python/ops/stateful_random_ops.py

This file is from TF 2.4?

And this issue does not happen anymore with a more recent TF version, TF 2.13 or so?

**Comment by albertz** [comment] 2023-12-08 22:43
(Closing, as the issue is not on RETURNN side. But please extend the relevant information as I asked so that it is clear what actual error you got here.)

**Closed** 2023-12-08 22:43 UTC

**Comment by jiangj-dc** [comment] 2023-12-11 17:38
This issue does not happen anymore with TF 2.13.

More information is included for the error output:

  File "returnn/returnn/tf/layers/base.py", line 1289, in LayerBase.var_creation_scope.<locals>.layer_custom_getter.<locals>.<lambda>
    line: fn_train=lambda: tf_util.dropout(
              param,
              keep_prob=1.0 - param_dropout,
              grad_checkpointing=True,
              seed=self.network.random.randint(2**31),
          ),
    locals:
      fn_train = <not found>
      tf_util = <global> <module 'returnn.tf.util.basic' from 'returnn/returnn/tf/util/basic.py'>
      tf_util.dropout = <global> <function dropout at 0x7f87a7ca7d30>
      param = <local> <tf.Variable 'conformer_block_01_ffmod_1_ff1/W:0' shape=(256, 1024) dtype=float32>
      keep_prob = <not found>
      param_dropout = <local> 0.06
      grad_checkpointing = <not found>
      seed = <not found>
      self = <local> <LinearLayer 'conformer_block_01_ffmod_1_ff1' out_type=Tensor{[B,T|'⌈((-199+time:var:extern_data:audio_features)+-200)/960⌉'[B],F|F'conformer_block_01_ffmod_1_ff1:feature-dense'(1024)]}>
      self.network = <local> <TFNetwork '' train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>>
      self.network.random = <local> RandomState(MT19937) at 0x7F86EA864940
      self.network.random.randint = <local> <built-in method randint of numpy.random.mtrand.RandomState object at 0x7f86ea864940>
  File "returnn/returnn/tf/util/basic.py", line 1872, in dropout
    line: rnd_state = StatelessRandomSeed.create(shape=noise_shape)
    locals:
      rnd_state = <not found>
      StatelessRandomSeed = <global> <class 'returnn.tf.util.basic.StatelessRandomSeed'>
      StatelessRandomSeed.create = <global> <bound method StatelessRandomSeed.create of <class 'returnn.tf.util.basic.StatelessRandomSeed'>>
      shape = <not found>
      noise_shape = <local> [256, 1024]
  File "returnn/returnn/tf/util/basic.py", line 4444, in StatelessRandomSeed.create
    line: key, counter = generator._prepare_key_counter(shape)
    locals:
      key = <not found>
      counter = <not found>
      generator = <local> <tensorflow.python.ops.stateful_random_ops.Generator object at 0x7f86dee2e880>
      generator._prepare_key_counter = <local> <bound method Generator._prepare_key_counter of <tensorflow.python.ops.stateful_random_ops.Generator object at 0x7f86dee2e880>>
      shape = <local> [256, 1024]
  File "lib/python3.8/site-packages/tensorflow/python/ops/stateful_random_ops.py", line 630, in Generator._prepare_key_counter
    line: counter = array_ops.bitcast(counter_key[:counter_size], dtypes.uint64)
    locals:
      counter = <not found>
      array_ops = <global> <module 'tensorflow.python.ops.array_ops' from 'lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py'>
      array_ops.bitcast = <global> <function bitcast at 0x7f87b4e79dc0>
      counter_key = <local> None
      counter_size = <local> 2
      dtypes = <global> <module 'tensorflow.python.framework.dtypes' from 'lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py'>
      dtypes.uint64 = <global> tf.uint64
TypeError: 'NoneType' object is not subscriptable
