### ISSUE TITLE
MetaDataset - DummyDataset Compatibility Issues

### ISSUE THREAD

**Issue by npwynands** [rwth-i6/returnn#305] opened 2020-06-15 12:56 UTC
For debugging purposes, I wanted to create a dummy dataset containing multimodal data. For this, I utilized [`MetaDataset`](https://github.com/rwth-i6/returnn/blob/master/MetaDataset.py#L111-L482) and [`DummyDataset`](https://github.com/rwth-i6/returnn/blob/master/GeneratingDataset.py#L670-L711)s.
But I had some issues creating a `MetaDataset` out of `DummyDataset`s. The `DummyDataset`s complained about given `seq_list_files` being "senseless", but the `MetaDataset` needed some sequence tags, which apparently could not be provided by the `DummyDataset`s automatically, because those where not initialized yet, when the `MetaDataset` requested them.

So I had to do the following work-around, which modifies the RETURNN source code:

**Step 1:**
Go to [`GeneratingDataset.py`](https://github.com/rwth-i6/returnn/blob/master/GeneratingDataset.py) to [`GeneratingDataset.init_seq_order`](https://github.com/rwth-i6/returnn/blob/master/GeneratingDataset.py#L55). In that function you find the assertion:
```python
assert not seq_list, "predefined order doesn't make sense for %s" % self.__class__.__name__
```
Disable that line (e.g. by commenting it out).

**Step 2:**
Create a `seq_list_file` for the dummy `MetaDataset` by creating an object:
```python        
{
  "translation": ["seq-0", "seq-1", ..., "seq-n"],
  "sprint": ["seq-0", "seq-1", ..., "seq-n"]
}
```
for the `train` (`n`=425706) and for the `dev32k` (`n`=3033) dataset, and dump each as a pickle file. The path to the files must be given to the dummy `MetaDataset` (cf. `get_dummy_meta_dataset` in the attached config file).

**Step 3:**
Make sure, that the sorting order of the train dummy `MetaDataset` is set to `"default"` and not `"random"`. Otherwise it will cause an error, because of an apparent missmatch between the `seq_list_file` order and the `DummyDataset`'s own internal seq order (?).

I assume, `MetaDataset` and `DummyDataset` are meant to be compatible without any work-around, hence this GitHub issue.

I attached you a simplified version of my config, which is already configured for the work-around, as well as the pre-generated dummy `seq_list_file`s. To disable the work-around, omit the steps explained above and disable the `"seq_list_file": seq_list_file` line in the `get_dummy_meta_dataset` function.

**Environment:**
- OS: Ubuntu 18 (local machine, not the cluster)
- Python 3.7.5
- TensorFlow 1.15.2
- RETURNN (commit 8595f10b03067b0a2253d0ee65d7dd7efd62ce76; 27th May, 15:40)

**Files:**
- Config: [meta-dummy-dataset.py.txt](https://github.com/rwth-i6/returnn/files/4780233/meta-dummy-dataset.py.txt)
- Dummy sequence sength files: [dummy_seq_list_files.zip](https://github.com/rwth-i6/returnn/files/4780207/dummy_seq_list_files.zip)

**Comment by albertz** [comment] 2020-06-15 14:44
This works all as intended.

The `assert` in `DummyDataset` could maybe be replaced by `NotImplementedError`. However, the `DummyDataset` is by design very simple. It was never planned to support this, and actually would complicate the logic quite a lot in `DummyDataset`. Maybe you could extend the documentation of `DummyDataset` to be more specific about this (although I think it's clear from the code, or not?).

Note that there are other datasets as well which don't support a predefined seq order. You can also surely imagine cases where this is simply not possible. I don't really see a problem in that. You will get an error that it is not possible (or not implemented/supported).

Or what exactly do you suggest to improve here?

I'm closing now, as I don't see anything really to be done here.

**Closed by albertz** 2020-06-15 14:44 UTC

**Comment by npwynands** [comment] 2020-06-15 15:28
The point of my issue is not that `DummyDataset` does not support pre-defined sequence order lists. My point is that I expected that `MetaDataset` would work with any (simple) `Dataset` and thus also with `DummyDataset`. Or in other words, I expected `DummyDataset` to behave like a normal `Dataset` from the outside (like a dummy, as the name suggests). The pre-defined sequence order list is just part of my simple work-around. It is used to circumvent the problem, that `DummyDataset` is not able to provide a sequence order list on its own when `MetaDataset` requests it on initialization, which leads to the error:
```shell
Reading sequence list for MetaDataset 'dev' from sub-dataset 'dev_sprint'
Traceback (most recent call last):
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/rnn.py", line 641, in main
    init(command_line_options=argv[1:])
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/rnn.py", line 401, in init
    init_data()
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/rnn.py", line 243, in init_data
    config, cache_byte_sizes[1], 'dev', **Dataset.get_default_kwargs_eval(config=config))
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/rnn.py", line 226, in load_data
    data = init_dataset(kwargs)
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/Dataset.py", line 1280, in init_dataset
    obj = clazz(**kwargs)
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/MetaDataset.py", line 221, in __init__
    self.seq_list_original = self._load_seq_list(seq_list_file)
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/MetaDataset.py", line 288, in _load_seq_list
    seq_list = default_dataset.get_all_tags()
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/Dataset.py", line 662, in get_all_tags
    all_tags[seq_idx] = self.get_tag(seq_idx)
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/GeneratingDataset.py", line 197, in get_tag
    self._check_loaded_seq_idx(seq_idx)
  File "/home/philipp/Documents/bachelor-thesis/returnn/repository/GeneratingDataset.py", line 73, in _check_loaded_seq_idx
    raise Exception("no data loaded yet")
Exception: no data loaded yet
```
when the sequence tags are requested via `GeneratingDataset.get_tag`.

As I said, in the end, my work-around is pretty simple. But I feel like it shouldn't be necessary to perform a work-around at all to achieve the behavior I expected.

So, it should be possible to create a `MetaDataset` out of `DummyDataset`s.

**Comment by albertz** [comment] 2020-06-15 15:41
But this is what I explained. `DummyDataset` is so simple, it does not support a predefined seq order.
Also, your assumption is wrong: Any normal dataset does not need to support this. This is some optional feature of a dataset. This feature is not supported by `DummyDataset`.

`MetaDataset` only supports sub-datasets which support this feature, though.

Btw, maybe you understood `MetaDataset` wrong. The idea is that all subdatasets provide the same set of sequences, but only different types of features (or other information) for the sequences. That is why `MetaDataset` first figures out the seq order (list of seq tags) and then tells each subdataset to use exactly these pre-defined seqs (defined by their seq tags).

So that is why it is totally correct that `MetaDataset` does not support `DummyDataset` just as-is.

Maybe you want to have another kind of `MetaDataset` which does not care at all about the actual sequences? I assume this is just for debugging? Maybe instead you could just extend `DummyDataset` to have multiple data-keys?

**Comment by npwynands** [comment] 2020-06-17 09:23
I think I understood `MetaDataset` correctly. You’re right, this is only for debugging purposes, where I don’t care about sequence orders. I just need multiple data keys, as in my true-data scenario.
If I find some time, I might look into extending `DummyDataset` with the ability to add multiple data keys...

**Comment by albertz** [comment] 2020-06-17 10:12
The code of `DummyDataset` is just 10 lines of code or sth like that. It's really trivial. :)
Sure, you could extend that to allow for all kinds of further usages (like proper use inside `MetaDataset`, all kinds of seq ordering/shuffling support, etc). But not sure if this is a good idea. (Also, you should not change the behavior. This `DummyDataset` is used in tests, which expect exactly this behavior, i.e. the same numbers coming out of it.)

`MetaDataset` cares about seq order. `DummyDataset` does not support that. That's why it does not work.
