### ISSUE TITLE
Control GPU Memory allocation 

### ISSUE THREAD

**Issue by akshatdewan** [rwth-i6/returnn#300] opened 2020-06-10 09:32 UTC
Hi, I am trying to limit the GPU memory allocation using the `tf.gpuOptions` in `tf.Session` config but do not see it getting reflected. 

I am modifying the `_make_tf_session` function in `TFEngine.py`  as 

```
def _make_tf_session(self):
    ...

    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
    opts["gpu_options"] = gpu_options
    # Note: We don't set intra_op_parallelism_threads and inter_op_parallelism_threads here anymore
    # because it is safer to do it via setup_tf_thread_pools() which we call very early.
    print("Setup tf.Session with options %r ..." % opts, file=log.v2)
    config = tf.ConfigProto(**opts)
    # config.gpu_options.allow_growth=True
    # For debugging, see tfdbg.LocalCLIDebugWrapperSession.
    self.tf_session = tf.Session(config=config)

```

But TF still seems to allocate ( as seen using `nvidia-smi`) all the available GPU memory to the process.

Do I need to make changes elsewhere in returnn code? 

Can it be related to the TF and CUDA versions I am using? ( I am using TF 1.13, CUDA 10.0.130 and Nvidia drivers 418.67 )

**Comment by albertz** [comment] 2020-06-10 09:44
Why do you need to modify the code for that? As you see in the code, it will take that options from your config file already. You can just set this in your config:
```
tf_session_opts = {"gpu_options": {"per_process_gpu_memory_fraction": 0.333}}
```
I would strongly suggest to avoid modifying the RETURNN code, unless it is really necessary.
If you use that setting, it might actually work already, because there are other places where it will also create a TF session, and maybe the first session creation is relevant.

**Comment by akshatdewan** [comment] 2020-06-10 10:01
Thanks, duly noted. 

But still the same result though, unfortunately.

I will try with some simpler TF code and see.

**Comment by albertz** [comment] 2020-06-10 10:11
I think you might also need `allow_growth`, like this:
```
tf_session_opts = {"gpu_options": {"per_process_gpu_memory_fraction": 0.333, "allow_growth": True}}
```

**Comment by akshatdewan** [comment] 2020-06-10 10:20
adding `allow_growth` does not help either. I will continue investigating and report back if I find a solution. Thanks!

**Comment by albertz** [comment] 2020-06-11 13:18
Have you tried with pure TF code? Does that work? So you are sure now this is a RETURNN issue? Can you show the pure TF code which works correctly?

**Comment by akshatdewan** [comment] 2020-06-11 13:21
Hi, yes, I tried with a very simple multiplication snippet and it works as expected. 

```
import tensorflow as tf
  
from numpy.random import default_rng

rng = default_rng()
vals = rng.standard_normal((100,100))
more_vals = rng.standard_normal((100,100))

# Initialize two constants
x1 = tf.constant(vals)
x2 = tf.constant(more_vals)

# Multiply
result = tf.multiply(x1, x2)

# Assume that you have 12GB of GPU memory and want to allocate ~4GB:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.1)

with tf.Session(config=tf.ConfigProto(gpu_options=gpu_options)) as sess:
# Initialize Session and run `result`
  output = sess.run(result)
  print(output)

```

**Comment by albertz** [comment] 2020-06-11 13:25
And what RETURNN example does not work correct?

**Comment by akshatdewan** [comment] 2020-06-11 14:34
I have tried two `rnn.py` tasks - `train` and  `search`. It was done via the [returnn-experiments](https://github.com/rwth-i6/returnn-experiments/tree/master/2018-asr-attention/librispeech/full-setup-attention) scripts [22_train.sh](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/22_train.sh) and [23_recog.sh](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/23_recog.sh).

None of the two worked as expected. The two processes continued to allocate all the available GPU memory regardless of the 33% limit allegedly imposed. 

It could be because of my `CUDA 10.0`. I will change that to `10.1` and test again.

**Comment by albertz** [comment] 2020-06-12 08:38
This pure TF code will reproduce the problem ([code link](https://github.com/albertz/playground/blob/master/tf-gpu-mem-fraction.py)):
```
import tensorflow as tf
from tensorflow.python.client import device_lib
import time

tf.compat.v1.disable_eager_execution()

v = tf.compat.v1.get_variable("var", shape=(100, 100))
result = v

# The following line will cause the full GPU mem allocation.
print(list(device_lib.list_local_devices()))

gpu_options = tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.1)

with tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(gpu_options=gpu_options)) as sess:
  sess.run(tf.compat.v1.global_variables_initializer())
  output = sess.run(result)
  print(output)

  print("press Ctrl+C to stop")
  while True:
    time.sleep(1)
```

**Comment by albertz** [comment] 2020-06-12 09:22
This sounds like [TenorFlow bug #9374](https://github.com/tensorflow/tensorflow/issues/9374).

**Comment by albertz** [comment] 2020-06-12 10:07
This should be fixed now in RETURNN. See latest referenced commit. Please report if there are further problems.

**Closed by albertz** 2020-06-12 10:07 UTC

**Comment by akshatdewan** [comment] 2020-06-12 10:28
Thanks! It works like a charm!

**Comment by albertz** [comment] 2020-06-12 11:10
Btw, you might also be interested in the TF 2 support, which should work now. See #283. If there are problems, please report in #283.

**Comment by akshatdewan** [comment] 2020-06-17 15:11
Which version of TF2 would you recommend? TF2.2.0?

**Comment by albertz** [comment] 2020-06-17 18:32
Yea, the latest one, TF 2.2.0.
