### ISSUE TITLE
mdlstm IAM demo crashes after loading train.2.h5

### ISSUE THREAD

**Issue by cwig** [rwth-i6/returnn#4] opened 2017-02-02 17:07 UTC
I ran the IAM demo and it crashes part way through epoch 2 right after loading train.2.h5. All of the other demos worked correctly. Here is a script of exactly what I was running: https://gist.github.com/cwig/315d212964542f7f1797d5fdd122891e

Let me know if I need to run anything differently. Thank you.

This is the traceback. 

train epoch 2, batch 190, cost:output 2.56628417969, elapsed 0:04:28, exp. remaining 1:04:21, complete 6.49%
1:04:21 [||||                               6.49%                                    ]running 2 sequence slices (442764 nts) of batch 191 on device gpu0
loading file features/raw/train.2.h5
TaskThread train failed
Unhandled exception <type 'exceptions.ValueError'> in thread <TrainTaskThread(TaskThread train, started daemon 140405735151360)>, proc 2207.
EXCEPTION
Traceback (most recent call last):
  File "/mnt/3TB_A/workspace/returnn_IAM/EngineTask.py", line 373, in run
    line: self.run_inner()
    locals:
      self = <local> <TrainTaskThread(TaskThread train, started daemon 140405735151360)>
      self.run_inner = <local> <bound method TrainTaskThread.run_inner of <TrainTaskThread(TaskThread train, started daemon 140405735151360)>>
  File "/mnt/3TB_A/workspace/returnn_IAM/EngineTask.py", line 466, in run_inner
    line: deviceRuns[i].allocate()
    locals:
      deviceRuns = <local> [<DeviceBatchRun(DeviceThread gpu0, started daemon 140405385864960)>]
      i = <local> 0
      allocate = <not found>
  File "/mnt/3TB_A/workspace/returnn_IAM/EngineTask.py", line 218, in allocate
    line: self.devices_batches = self.parent.allocate_devices(self.alloc_devices)
    locals:
      self = <local> <DeviceBatchRun(DeviceThread gpu0, started daemon 140405385864960)>
      self.devices_batches = <local> [[<Batch start_seq:3846, #seqs:2>]]
      self.parent = <local> <TrainTaskThread(TaskThread train, started daemon 140405735151360)>
      self.parent.allocate_devices = <local> <bound method TrainTaskThread.allocate_devices of <TrainTaskThread(TaskThread train, started daemon 140405735151360)>>
      self.alloc_devices = <local> [<Device.Device object at 0x7fb2c2ba19d0>]
  File "/mnt/3TB_A/workspace/returnn_IAM/EngineTask.py", line 84, in allocate_devices
    line: success, batch_adv_idx = self.assign_dev_data(device, batches)
    locals:
      success = <not found>
      batch_adv_idx = <not found>
      self = <local> <TrainTaskThread(TaskThread train, started daemon 140405735151360)>
      self.assign_dev_data = <local> <bound method TrainTaskThread.assign_dev_data of <TrainTaskThread(TaskThread train, started daemon 140405735151360)>>
      device = <local> <Device.Device object at 0x7fb2c2ba19d0>
      batches = <local> [<Batch start_seq:3349, #seqs:2>]
  File "/mnt/3TB_A/workspace/returnn_IAM/EngineTask.py", line 54, in assign_dev_data
    line: return assign_dev_data(device, self.data, batches)
    locals:
      assign_dev_data = <global> <function assign_dev_data at 0x7fb2ca2ab230>
      device = <local> <Device.Device object at 0x7fb2c2ba19d0>
      self = <local> <TrainTaskThread(TaskThread train, started daemon 140405735151360)>
      self.data = <local> <HDFDataset.HDFDataset object at 0x7fb2c8056690>
      batches = <local> [<Batch start_seq:3349, #seqs:2>]
  File "/mnt/3TB_A/workspace/returnn_IAM/EngineUtil.py", line 23, in assign_dev_data
    line: if load_seqs: dataset.load_seqs(batch.start_seq, batch.end_seq)
    locals:
      load_seqs = <local> True
      dataset = <local> <HDFDataset.HDFDataset object at 0x7fb2c8056690>
      dataset.load_seqs = <local> <bound method HDFDataset.load_seqs of <HDFDataset.HDFDataset object at 0x7fb2c8056690>>
      batch = <local> <Batch start_seq:3349, #seqs:2>
      batch.start_seq = <local> 3349
      batch.end_seq = <local> 3351
  File "/mnt/3TB_A/workspace/returnn_IAM/CachedDataset.py", line 140, in load_seqs
    line: self._load_seqs_with_cache(start, end)
    locals:
      self = <local> <HDFDataset.HDFDataset object at 0x7fb2c8056690>
      self._load_seqs_with_cache = <local> <bound method HDFDataset._load_seqs_with_cache of <HDFDataset.HDFDataset object at 0x7fb2c8056690>>
      start = <local> 3349
      end = <local> 3351
  File "/mnt/3TB_A/workspace/returnn_IAM/CachedDataset.py", line 168, in _load_seqs_with_cache
    line: self.load_seqs(start, end, with_cache=False)
    locals:
      self = <local> <HDFDataset.HDFDataset object at 0x7fb2c8056690>
      self.load_seqs = <local> <bound method HDFDataset.load_seqs of <HDFDataset.HDFDataset object at 0x7fb2c8056690>>
      start = <local> 3349
      end = <local> 3359
      with_cache = <not found>
  File "/mnt/3TB_A/workspace/returnn_IAM/CachedDataset.py", line 143, in load_seqs
    line: super(CachedDataset, self).load_seqs(start, end)
    locals:
      super = <builtin> <type 'super'>
      CachedDataset = <global> <class 'CachedDataset.CachedDataset'>
      self = <local> <HDFDataset.HDFDataset object at 0x7fb2c8056690>
      load_seqs = <not found>
      start = <local> 3349
      end = <local> 3359
  File "/mnt/3TB_A/workspace/returnn_IAM/Dataset.py", line 159, in load_seqs
    line: self._load_seqs(start, end)
    locals:
      self = <local> <HDFDataset.HDFDataset object at 0x7fb2c8056690>
      self._load_seqs = <local> <bound method HDFDataset._load_seqs of <HDFDataset.HDFDataset object at 0x7fb2c8056690>>
      start = <local> 3349
      end = <local> 3359
  File "/mnt/3TB_A/workspace/returnn_IAM/HDFDataset.py", line 152, in _load_seqs
    line: self._set_alloc_intervals_data(idc, data=fin['inputs'][p[0] : p[0] + l[0]][...])
    locals:
      self = <local> <HDFDataset.HDFDataset object at 0x7fb2c8056690>
      self._set_alloc_intervals_data = <local> <bound method HDFDataset._set_alloc_intervals_data of <HDFDataset.HDFDataset object at 0x7fb2c8056690>>
      idc = <local> 3358
      data = <not found>
      fin = <local> <HDF5 file "train.2.h5" (mode r)>, len = 5
      p = <local> array([110348430,     25353,      1172]), len = 3
      l = <local> array([151211,     40,      2], dtype=int32), len = 3
  File "/mnt/3TB_A/workspace/returnn_IAM/CachedDataset.py", line 220, in _set_alloc_intervals_data
    line: self.alloc_intervals[idi][2][o:o + l] = x
    locals:
      self = <local> <HDFDataset.HDFDataset object at 0x7fb2c8056690>
      self.alloc_intervals = <local> [(0, 1321, array([[ 0.],
                                            [ 0.],
                                            [ 0.],
                                            ..., 
                                            [ 0.],
                                            [ 0.],
                                            [ 0.]], dtype=float32)), (1329, 1333, array([[ 0.],
                                            [ 0.],
                                            [ 0.],
                                            ..., 
                                            [ 0.],
                                            [ 0.],
                                            [ 0.]], dtype=float32)), (1417, 1420, array([[ 0.],
                                            [ 0.],
                                       ..., len = 52
      idi = <local> 48
      o = <local> 1824769
      l = <local> 151211
      x = <local> array([[ 0.],
                         [ 0.],
                         [ 0.],
                         ..., 
                         [ 0.],
                         [ 0.],
                         [ 0.]], dtype=float32), len = 151211, _[0]: {len = 1}
ValueError: could not broadcast input array from shape (151211,1) into shape (107131,1)

**Comment by doetsch** [comment] 2017-02-03 10:04
Unfortunately I am not able to reproduce the error. Are you using the most recent commit? You can also try to deactivate caching by setting cache_size to "8G".

**Comment by pvoigtlaender** [comment] 2017-02-03 11:49
I was able to reproduce it:

ValueError: could not broadcast input array from shape (151211,1) into shape (107131,1)

KeyboardInterrupt
train epoch 2, batch 191, cost:output 2.81097157796, elapsed 0:07:17, exp. remaining 1:44:52, complete 6.49%
1:44:52 [|||||||||||||                                                                                               6.49%

But I don't know yet, what is the problem here

**Comment by pvoigtlaender** [comment] 2017-02-06 12:31
for a quick fix you could try to put all the data into one file instead of two, although this does not solve the actual issue ofcourse.
You can also try an older commit. The demo used to work in earlier commits. If you can find out, which commit broke it, then it might be easy to fix it

**Comment by cwig** [comment] 2017-02-06 15:42
Thanks for looking into this. I did try putting all the training data in one file and I still had the issue. I modified the create_IAM_dataset.py file on line 203-209.

I'll try an older commit.

**Comment by cwig** [comment] 2017-02-08 16:46
This didn't solve the actual problem, but it worked when I reverted back to commit 82be088 (https://github.com/rwth-i6/returnn/commit/82be088899cf7ba2f4249fc42aa595375d3fcd99)

**Comment by pvoigtlaender** [comment] 2017-02-08 16:56
Is this the last commit which works? It would be very helpful to find it, so we can see which change was the problem.

**Comment by cwig** [comment] 2017-02-08 16:59
I'm not sure. I have only tried two so far. a925c7a did not work so it is somewhere between a925c7a and 82be088.

**Comment by doetsch** [comment] 2017-03-03 00:55
Could you try the most recent commit? There seems to be an issue with the cache size calculation on some few machines and it took me a while to reproduce it. Hard coding it to 16GB in config_real as done by commit 2d1744c014b14f8a3f5d8c095993ed97d505a51b resolved the issue for me on this machine.

**Comment by pvoigtlaender** [comment] 2017-03-03 13:33
With cache_size set to 256G (as in the latest version in the repository) it works with the latest commit now. There seems to be a problem with the size calculation for two-dimensional data. So for now just set the cache_size real high

**Comment by doetsch** [comment] 2017-03-06 20:26
The fix has been confirmed on three independent machines. Therefore I am closing this issue.

**Closed by doetsch** 2017-03-06 20:26 UTC
