### ISSUE TITLE
Improve documentation about DimensionTag

### ISSUE THREAD

**Issue by ashu5644** [rwth-i6/returnn#258] opened 2019-12-17 09:33 UTC
Hi i am doing LM training. Alongwith normal text data i am also passing an extra array with each sentence array. I have used a new variable data(extra_data) along with data(delayed) . So i have added relevant changes in LMDataset file, same as for data(delayed). and also added that data(extra_data) in lm config file also for num_outputs. And in network along with a linear layer of data(delayed) i have used another linear layer whose input is data(extra_data). When i pass output of both layers in lstm layer as input with 'from' argument of layer as a list. I got error in lstm0 layer formation as:
self.placeholder.shape.ndims= <local> 4
self.batch_ndim=<local>3
Assertion error
assert self.placeholder.shape.ndims==self.batch_ndim
On debugging i found out that time dimension of both inputs are being treated as seperate and their concatenation is generating four dimensions i.e batch,time_delayed,time_extra_data,feature. How to resolve this issue?

**Comment by albertz** [comment] 2019-12-17 09:47
Hi,

Multiple things:

* I would recommend to not use `data:delayed` anymore. You can do the same directly in the network. E.g. via this:
```
   "lm_input0": {"class": "copy", "from": "data:%s" % target},
   "lm_input1": {"class": "prefix_in_time", "from": "lm_input0", "prefix": 0},
   "lm_input2": {"class": "slice", "from": "lm_input1", "axis": "t", "slice_end": -1},
   "lm_input": {"class": "reinterpret_data", "from": "lm_input2", "size_base": "lm_input0"},
```

* Use `debug_print_layer_output_template = True` in the config, and then post the debug output while the network is constructed. This output is anyway very useful to understand why the shape is such.

* The issue is probably because Returnn thinks that `data:delayed` and `data` have two different time axes. How should it know that they are the same? But you can tell it explicitly so. It will look sth like this in your config:
```
from TFUtil import DimensionTag
time_tag = DimensionTag(kind=DimensionTag.Types.Spatial, description="time")

extern_data = { 
  'data': {"dim": 40, "sparse": True, "same_dim_tags_as": {"t": time_tag}},
  'delayed': {"dim": 40, "sparse": True, "same_dim_tags_as": {"t": time_tag}},
}
```

@kazuki-irie might also be able to help.

**Comment by ragnarlbrok** [comment] 2019-12-17 10:12
Thank you very much @albertz for quick reply. It's working now.

**Comment by patrick-wilken** [comment] 2019-12-17 15:23
@talkhouli also had to ask me about this. It really isn't obvious that this has to be configured because you have to dive pretty deep into the code to see that there is logic depending on matching time axes. So at least it would be good if we could document it better. And I would also make it easier to configure, something like
```
extern_data = { 
  'data': {"dim": 40, "sparse": True},
  'delayed': {"dim": 40, "sparse": True, "same_time_axis_as": "data"},
}
```

**Comment by albertz** [comment] 2019-12-17 15:29
@patrick-wilken @talkhouli Yes, as said, better do not use `data:delayed` at all, then you don't have this problem at all

But otherwise, I agree, `Data` maybe should be better documented, along with what a time/spatial dimension is and means, and `DimensionTag` in that context.

**Comment by albertz** [comment] 2021-11-26 10:40
Since this report, we have improved a lot on the documentation. I'm closing this now.

Please open a new issue if you have some further specific question, find some aspects in the documentation still lacking, some other issue, or whatever.

**Closed by albertz** 2021-11-26 10:40 UTC
