### ISSUE TITLE
Non-deterministic memory leak

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1111] opened 2022-09-01 11:59 UTC
After switching from our default hybrid setup to a new `returnn-common` based one, I encounter CPU-memory issues in training. The problem is that it is not clear when the memory increase happens, the initial memory consumption is similar. During manual observation I saw that for some new sub-epochs the memory consumption just randomly increased by 4 Gb, without any apparent reason. For other new sub-epochs nothing changed.

I will check if this is somehow related to #1109.

**Comment by albertz** [comment] 2022-09-01 12:02
We have had memory leaks already before in the case of frequent re-inits of the network. Specifically, this was #990.

**Comment by albertz** [comment] 2022-09-23 09:34
@JackTemaki @Atticus1806 Did you check whether the recent fix for #1109 also resolved this issue? In that case, it is a duplicate of #990.

**Comment by Atticus1806** [comment] 2022-09-23 09:35
Yes should be fixed. Was able to reduce the mem usage from ~20GB to less than 4GB.

**Closed** 2022-09-23 09:35 UTC
