### ISSUE TITLE
a bug related to Tensorflow was fixed. but was it the right way to do?

### ISSUE THREAD

**Issue by sephiroce** [rwth-i6/returnn#105] opened 2019-01-06 01:10 UTC
Thank you for the wonderful open source project.
I'm planning to use this open source as a baseline system of my personal research project.
I use 2080Ti FE. As far as I know, I should use CUDA 10.0 for this device.
Officially Tensorflow doesn't support CUDA 10.0 thus I installed Tensorflow from the newest source code (Jan. 4. 2019).

During training demo scripts, I faced a kind of famous bug related to compiling string_view.h with nvcc.
I fixed and the script is working. But I'm not sure the measures were appropriate.
I would appreciate if you review the below.

Command: `${returnn}/demos/demo.sh tf-attention`
I followed the simplest solution on https://github.com/tensorflow/tensorflow/issues/22766 (the issue is still open)
```
495   static constexpr size_type CheckLengthInternal(size_type len) {
496     // return ABSL_ASSERT(len <= kMaxSize), len;  // original source code.
497     return 0, len; // I simply replaced the assert with 0.
498   }
```

**Comment by sephiroce** [comment] 2019-01-06 01:39
I think it would be better pull request those issues.

**Comment by sephiroce** [comment] 2019-01-06 01:51
I decided to reopen this issue since I'm still wondering the issue related to `string_view.h` was fixed or not.

**Comment by sephiroce** [comment] 2019-01-06 01:51
I decided to reopen this issue since I'm still wondering the issue related to `string_view.h` was fixed or not.

**Comment by albertz** [comment] 2019-01-06 13:30
This is also a duplicate of #87 (or at least very related), so I think we can close this (but leave #87 open for now).
I'm still not sure whether I should add a workaround to Returnn for that. I actually was hoping that TF would fix this soon.

**Comment by albertz** [comment] 2019-01-06 13:31
But yes, the workaround should work.

**Closed by albertz** 2019-01-06 13:30 UTC
